Repository EnjoytripDS/Travelary_Frontend, pull requests merged in 2023-05, with the labels that each got.

#2 [Feature/01] 마이페이지 구현
  package-lock.json
  package.json
  src/components/common/TheHeader.vue
  src/components/users/UserLogin.vue
  src/components/users/UserMyPage.vue
  src/components/users/UserRegister.vue
  src/components/users/mypage/MyPageChangePwd.vue
  src/components/users/mypage/MyPageDropOut.vue
  src/components/users/mypage/MyPageInfo.vue
  src/router/index.js
  src/store/index.js
  src/store/modules/User.js
Labels: ✨Feat

#5 [feature/03] UI 디자인 변경 및 여행 계획 UI
  .gitignore
  README.md
  package-lock.json
  src/App.vue
  src/assets/image/home/home1.jpg
  src/assets/image/home/home2.jpg
  src/assets/image/home/home3.jpg
  src/assets/image/home/home4.jpg
  src/assets/image/tripimage.jpg
  src/assets/tripImage.jpg
  src/components/common/TheContentHeader.vue
  src/components/common/TheHeader.vue
  src/components/tripplan/AttractionList.vue
  src/components/tripplan/SearchAttraction.vue
  src/components/tripplan/TripInfoForm.vue
  src/components/tripplan/TripTimeline.vue
  src/components/tripplan/TripTitleBanner.vue
  src/components/users/mypage/MyPageInfo.vue
  src/store/index.js
  src/store/modules/TripPlan.js
  src/views/AppHome.vue
  src/views/AppTripPlan.vue
Labels: ✨Feat

#7 [Feature 04] Jwt 로그인 구현
  package-lock.json
  package.json
  src/components/common/TheHeader.vue
  src/components/users/UserLogin.vue
  src/components/users/UserRegister.vue
  src/components/users/mypage/MyPageChangePwd.vue
  src/components/users/mypage/MyPageInfo.vue
  src/router/index.js
  src/store/modules/User.js
Labels: bug, ✨Feat

#8 Fix: git conflict 에러 수정
  src/components/users/mypage/MyPageInfo.vue
Labels: bug

#10 [Feature/05] search attraction kakaomap
  src/components/tripplan/SearchAttraction.vue
  src/components/tripplan/TripInfoForm.vue
  src/components/tripplan/item/SelectGugun.vue
  src/components/tripplan/item/SelectSido.vue
  src/store/modules/TripPlan.js
  src/views/AppTripPlan.vue
Labels: ✨Feat

#11 [Fix/02] QnA 보드 수정
  src/components/qnaboard/QnaBoardCreate.vue
  src/components/qnaboard/QnaBoardDetail.vue
  src/components/qnaboard/QnaBoardUpdate.vue
  src/components/users/UserLogin.vue
  src/store/modules/QnaBoard.js
  src/store/modules/User.js
Labels: bug

#15 [Feature/06] 게시판 댓글 구현
  src/components/common/TheHeader.vue
  src/components/qnaboard/QnaBoardDetail.vue
  src/components/qnaboard/comment/BoardCommentCreate.vue
  src/components/qnaboard/comment/BoardCommentList.vue
  src/router/index.js
  src/store/modules/QnaBoard.js
Labels: ✨Feat

#14 [Feature/07] Trip Plan Stepper(1)
  src/components/tripplan/AttractionList.vue
  src/components/tripplan/SearchAttraction.vue
  src/components/tripplan/TripInfoForm.vue
  src/components/tripplan/item/AttractionCardList.vue
  src/components/tripplan/item/SelectGugun.vue
  src/components/tripplan/item/SelectSido.vue
  src/components/tripplan/item/SelectedAttractionCardList.vue
  src/store/modules/TripPlan.js
  src/views/AppTripPlan.vue
Labels: ✨Feat

#18 [Feature/08] 게시글 작성 시 이미지 파일 업로드 기능
  src/components/qnaboard/QnaBoardCreate.vue
  src/components/qnaboard/QnaBoardDetail.vue
  src/components/qnaboard/QnaBoardList.vue
  src/components/qnaboard/QnaBoardUpdate.vue
  src/components/qnaboard/comment/BoardCommentCreate.vue
  src/components/qnaboard/comment/BoardCommentList.vue
  src/store/modules/QnaBoard.js
Labels: ✨Feat

#20 [Feature/09] my trip
  src/components/TheKakaoMap.vue
  src/components/tripplan/SearchAttraction.vue
  src/components/tripplan/TripTimeline.vue
  src/components/tripplan/item/AttractionCardList.vue
  src/components/tripplan/item/SelectedAttractionCardList.vue
  src/store/modules/TripPlan.js
  src/views/AppTripPlan.vue
Labels: ✨Feat

#24 [Fix/03] 마이페이지 및 게시글 오류 수정
  public/index.html
  src/App.vue
  src/components/common/TheHeader.vue
  src/components/qnaboard/QnaBoardDetail.vue
  src/components/qnaboard/QnaBoardUpdate.vue
  src/components/users/UserMyPage.vue
  src/components/users/UserRegisterCheck.vue
  src/components/users/mypage/MyPageChangePwd.vue
  src/components/users/mypage/MyPageDropOut.vue
  src/components/users/mypage/MyPageInfo.vue
  src/router/index.js
  src/store/modules/QnaBoard.js
  src/store/modules/User.js
Labels: bug, ✨Feat

#27 [Feature/12] Trip List Ui 구현
  src/assets/image/home/homeBottom1.jpg
  src/assets/image/home/homeBottom2.jpg
  src/components/common/TheFooter.vue
  src/components/tripplan/item/AttractionCardList.vue
  src/components/tripplan/item/SelectedAttractionCardList.vue
  src/store/modules/User.js
  src/views/AppTripList.vue
Labels: bug, ✨Feat

#28 [Feature/13] 로고 구현
  public/favicon.ico
  src/assets/TravelaryLogo.png
  src/assets/logo.png
  src/components/common/TheHeader.vue
  src/components/qnaboard/QnaBoardDetail.vue
  src/components/qnaboard/QnaBoardUpdate.vue
  src/store/modules/QnaBoard.js
Labels: ✨Feat

#29 [Fix/04] 컴파일 에러 수정
  src/components/tripplan/item/SelectedAttractionCardList.vue
Labels: bug

#31 [Feature/14] home image
  public/favicon.ico
  src/assets/TravelaryLogo.png
  src/assets/image/home/homeBottom2.jpg
  src/assets/image/home/homeBottom3.jpg
  src/assets/image/home/homeBottom4.jpg
  src/assets/image/home/homeBottom5.jpg
  src/assets/image/home/homeBottom6.jpg
  src/assets/image/home/homeBottom7.jpg
  src/assets/image/home/homeBottom8.jpg
  src/assets/image/home/homeBottom9.jpg
  src/components/qnaboard/QnaBoardDetail.vue
  src/views/AppHome.vue
Labels: bug, ✨Feat

#32 Fix: 게시글 제목 수정
  src/components/qnaboard/QnaBoardDetail.vue
Labels: bug
